[package]
name = "_8080"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["rlib"]

[dependencies]
disclose = "0"

[features]
default = ["std"]
std = []
open = []

[[example]]
name = "demo"
required-features = ["std"]

